
// Bonus Question for 2 points for any correct answer:
// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

//By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

func generateFibannciSeries() -> [Int] {
    var fSeries: [Int] = [1, 2]
    var found = false
    var i = 0
    while (!found) {
        let nextNumber = fSeries[i] + fSeries[i+1]
        if nextNumber > 4000000 {
            found = true
        } else {
            fSeries.append(nextNumber)
        }
        i++
    }
    return fSeries
}

let fabSeries = generateFibannciSeries()
var sum = 0
for number in fabSeries {
    if number%2 == 0 {
        sum+=number
    }
}

print (sum) // 4,613,732